# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Security Ramblings
title_separator: "|"
email: kristian@bodeholt.com
description: >- # this means to ignore newlines until "baseurl:"
  Security Ramblings by Kristian Bodeholt
url: "https://bodeholt.com"
twitter_username: bodeholt
github_username: kbodeholt
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kristian Bodeholt"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Father² & Husband, Pragmatic Technologist, IT Security Viking & Danish Army Veteran. Connected since 28.8k."
  location: "Aarhus, Denmark"
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kristian@bodeholt.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kristianbodeholt"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bodeholt"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://infosec.exchange/@kbodeholt"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/kbodeholt"
    - label: "Keybase"
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/kbodeholt"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/kristian.bodeholt"
      
social:
  type:  person
  name:  Kristian Bodeholt
  links:
    - "https://twitter.com/bodeholt"
    - "https://www.linkedin.com/in/kristianbodeholt/"
    - "https://www.facebook.com/kristian.bodeholt"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
